# Generated by Django 3.1 on 2021-03-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_news_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='news',
            name='background_picture',
            field=models.ImageField(default='default.jpg', upload_to='news_pictures/'),
        ),
        migrations.AddField(
            model_name='news',
            name='cover_picture',
            field=models.ImageField(default='default.jpg', upload_to='news_pictures/'),
        ),
    ]
