# Generated by Django 3.1 on 2021-03-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Not picked yet', max_length=6)),
                ('animal_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], default='Not picked yet', max_length=30)),
                ('condition', models.CharField(choices=[('Neutered', 'Neutered'), ('Spayed', 'Spayed')], default='Not picked yet', max_length=10)),
                ('health_status', models.BooleanField(default=True)),
                ('adoption_status', models.BooleanField(default=False)),
                ('story', models.TextField()),
                ('picture', models.ImageField(default='default.jpg', upload_to='animals_pictures/')),
            ],
        ),
    ]
