# Generated by Django 3.1 on 2021-03-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Rabies', 'Rabies'), ('Canine parvovirus', 'Canine parvovirus'), ('Canine hepatitis', 'Canine hepatitis')], default='Not necessary', max_length=50)),
                ('times_per_year', models.IntegerField()),
            ],
        ),
    ]
