# Generated by Django 3.1 on 2021-03-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0002_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(default='Not necessary', max_length=50),
        ),
    ]
