# Generated by Django 3.1 on 2021-03-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0004_animal_vaccines'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
