# Generated by Django 3.1 on 2021-03-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0005_animal_animal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
